```{r}
library(tidyverse)
library(gridExtra)
library(grid)
theme_set(theme_bw(base_size=10))
theme_update(panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  plot.title = element_text(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank(),
  panel.margin = unit(0, "lines"),
  strip.background = element_blank(),
  panel.border = element_blank(),
  legend.position = "none", 
  strip.text.x = element_text(margin = margin(0,0,0,0, "cm")))
```


```{r}
FST_win <- read.table("~/Documents/UMD/Replicated_cry_crosses/parents/FST/weirfst_benzon_field_parents_40.windowed.weir.fst", header = T) %>% mutate(CHR = str_replace_all(CHROM, "Hz_", ""))

FST_filter <- subset(FST_win, N_VARIANTS > 10)

FST_filter$ztrans <- scale(FST_filter$WEIGHTED_FST, center = TRUE, scale = TRUE) #ztransformation

hist(FST_filter$ztrans, breaks = 100)

hi_wcFST1 <- subset(FST_filter, ztrans > 6)
print(min(hi_wcFST1$WEIGHTED_FST))
```

```{r}
#jpeg("~/Documents/UMD/Replicated_cry_crosses/parents/FST/weirfst_GAR_benzon_field_40k1k.jpg", width = 12, height = 6, units = "cm", res = 700)

FST_win %>%
  filter(N_VARIANTS > 10) %>%
  ggplot(aes(y = WEIGHTED_FST, x = as.numeric(BIN_START))) +
  geom_hline(yintercept = 0.2, color = "grey", cex = 0.1, alpha = 0.3) +
  geom_hline(yintercept = 0.4, color = "grey", cex = 0.1, alpha = 0.3) +
  geom_hline(yintercept = 0.6, color = "grey", cex = 0.1, alpha = 0.3) +
  geom_hline(yintercept = 0.8, color = "grey", cex = 0.1, alpha = 0.3) +
  geom_hline(yintercept = 1, color = "grey", cex = 0.1, alpha = 0.3) +
  geom_point(alpha = 0.3, cex = 0.2, aes(color = as.factor(CHR))) +
  scale_color_manual(values = rep(c("grey15", "grey65"), times = 24)) +
  labs(x = "Chromosome", y = "FST") +
  facet_wrap(~as.numeric(CHR), strip.position="bottom", nrow = 1, scales = "free_x") +
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) +
  theme(text=element_text(size=9)) 

#dev.off()
```

```{r}
FST_win %>% filter(N_VARIANTS > 10) %>%
  summarize(min = min(WEIGHTED_FST), max = max(WEIGHTED_FST), mean = mean(WEIGHTED_FST))

```